# SAMPLE INFORMATION

# format is treatment_vs_control
comparisons: 
  - fpa8_vs_col0
  - 35SFPA_vs_col0
  - vir1_vs_VIRc

# conds to use for merged assembly
assembly_conds:
  - col0
  - fpa8
  - 35SFPA

# ANNOTATION FILENAMES

gtf_fn: ../annotations/Araport11_GFF3_genes_transposons.201606.no_chr.gtf
fasta_fn:  ../annotations/Arabidopsis_thaliana.TAIR10.dna.toplevel.fa

# MAPPING PARAMETERS

minimap2_parameters:
  max_intron_size: 20000
  annot_intron_bonus: 12


# APA PARAMETERS:

d3pendr_parameters:
  min_read_overlap: 0.2
  nboots: 999
  use_gamma_model: True
  test_homogeneity: False
